let a = new Date()
console.log(a)
console.log(a.getFullYear())
console.log(a.getMonth())
console.log(a.getDate())
console.log(a.getDay())
console.log(a.getHours())
console.log(a.getMinutes())
console.log(a.getSeconds())
console.log(a.getMilliseconds())
console.log(a.getTime())
console.log(a.getUTCDate())
console.log(a.toLocaleTimeString())
console.log(a.toTimeString())
console.log(a.toISOString())
console.log(a.toLocaleDateString())

console.log("------------------------------")
console.log(Math.round(4.4))
console.log(Math.round(4.5))
console.log(Math.round(4.6))
console.log(Math.sqrt(8))
console.log(Math.pow(2.8284271247461903 , 2))

